version: '3.1'
services:
#  API:
#    image: 'webapp2-ticketing'
#    ports:
#      - "8081:8081"
#    depends_on:
#      - KEYCLOAK
#      - PostgreSQL
#
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=1234
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
#      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak.wa2_polito_letduchidegliabruzzi_default:8080/realms/myrealm
#      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET-URI=http://keycloak.wa2_polito_letduchidegliabruzzi_default:8080/realms/myrealm/protocol/openid-connect/certs

  PostgreSQL:
    image: postgres
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  KEYCLOAK:
    image: arashhonarvar93/web2-keycloak:1.2
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

